[package]
name = "malware"
version = "0.1.0"
authors = ["reverser"]
edition = "2018"

[dependencies]
enigo="*"
libc="*"

[profile.dev]
opt-level='z'
lto=true
codegen-units=1

[profile.release]
opt-level='z'
lto=true
codegen-units=1
